---
eo:
  admin:
    custom_emojis:
      batch_copy_error: 'Eraro okazis dum kopiado de iom da elektitaj emoĝioj: %{message}'
      batch_error: 'Eraro okazis: %{message}'
    settings:
      captcha_enabled:
        title: Postuli, ke novaj uzantoj solvi CAPTCHA-on por ke oni konfirmu sian konton
      hide_followers_count:
        desc_html: Ne montri la kvanton de sekvantoj en profiloj de uzantoj
        title: Kaŝi la kvanton de sekvantoj
      other:
        title: Aliaj
      outgoing_spoilers:
        desc_html: Elsendante la afiŝoj al aliaj instancoj, aldoni ĉi tiun averton al afiŝoj, kiuj ne havas averton. Ĝi estas utila, se via instanco temas pri enhavo, kiun aliaj instancoj volus kovri per averto. Ambaŭ plurmedioj estos markita kiel tiklaj.
        title: Averto por elsenditaj afiŝoj
