---
fa:
  admin:
    settings:
      hide_followers_count:
        title: نهفتن تعداد پی‌گیران
      other:
        title: ديگر
  appearance:
    localization:
      glitch_guide_link: https://crowdin.com/project/glitch-soc
