---
da:
  simple_form:
    hints:
      defaults:
        setting_show_followers_count: Vis antal følgere på din profil. Hvis du skjuler antallet af følgere, vil det også være skjult for dig selv, og nogle apps kan vise et negativt antal.
    labels:
      defaults:
        setting_default_content_type: Standardformat for indlæg
        setting_default_content_type_html: HTML
        setting_default_content_type_markdown: Markdown
        setting_default_content_type_plain: Simpel tekst
        setting_favourite_modal: Vis bekræftelsesdialog før favoritmarkering (gælder kun for Glitch-varianten)
        setting_show_followers_count: Vis antal følgere
        setting_system_emoji_font: Brug systemets standardskrifttype til emojis (gælder kun for Glitch-varianten)
