---
it:
  simple_form:
    hints:
      defaults:
        setting_hide_followers_count: Nascondi il numero di seguaci di chiunque, incluso il tuo profilo. Alcune applicazioni potrebbero mostrare un numero negativo di seguaci.
    labels:
      defaults:
        setting_hide_followers_count: Nascondi il tuo numero di seguaci
