---
zh-CN:
  simple_form:
    glitch_only: glitch-soc
    hints:
      defaults:
        setting_default_content_type_html: 在撰写嘟文时，除非另有指定，假定它们使用原始 HTML 语言撰写
        setting_default_content_type_markdown: 在撰写嘟文时，除非另有指定，假定它们使用 Markdown 进行富文本格式化
        setting_default_content_type_plain: 在撰写嘟文时，除非另有指定，假定它们是没有特殊格式的纯文本（默认的 Mastodon 行为）
        setting_default_language: 你的嘟文语言可以自动检测，但不一定准确
        setting_hide_followers_count: 对所有人隐藏您的粉丝数，包括您在内。一些应用程序可能显示负粉丝数。
        setting_skin: 更换为所选择的 Mastodon 风格
    labels:
      defaults:
        setting_default_content_type: 嘟文默认格式
        setting_default_content_type_html: HTML
        setting_default_content_type_markdown: Markdown
        setting_default_content_type_plain: 纯文本
        setting_favourite_modal: 在点赞嘟文前询问我 (仅限于 Glitch 风格)
        setting_hide_followers_count: 隐藏你的粉丝数
        setting_skin: 皮肤
        setting_system_emoji_font: 使用系统自带表情 (仅限于 Glitch 风格)
      notification_emails:
        trending_link: 新热门链接需要审核
        trending_status: 新热门嘟文需要审核
        trending_tag: 新热门话题需要审核
