---
hi:
  simple_form:
    hints:
      defaults:
        setting_show_followers_count: आपकी प्रोफ़ाइल पर आपके अनुयायियों की संख्या दिखाएँ। यदि आप अपने अनुयायियों की संख्या छिपाते हैं, तो यह आपसे भी छिपी रहेगी, और कुछ एप्लिकेशन नकारात्मक अनुयायियों की संख्या प्रदर्शित कर सकते हैं।
    labels:
      defaults:
        setting_show_followers_count: अपने अनुयायियों की संख्या दिखाएँ
