---
pl:
  simple_form:
    glitch_only: glitch-soc
    hints:
      defaults:
        setting_default_content_type_html: Jeżeli nie powiedziano inaczej, załóż, że wpisy są pisane w HTML
        setting_default_content_type_markdown: Jeżeli nie powiedziano inaczej, załóż, że wpisy są pisane w Markdown
        setting_default_content_type_plain: Jeżeli nie powiedziano inaczej, załóż, że wpisy zawierają jedynie czysty tekst (domyślne zachowane Mastodonu)
        setting_default_language: Język Twoich wpisów może zostać wykryty automatycznie, aczkolwiek poprawność działania tej fukcji nie jest gwarantowana
        setting_skin: Zmienia wygląd używanej odmiany Mastodona
    labels:
      defaults:
        setting_default_content_type: Domyślny format wpisów
        setting_default_content_type_html: HTML
        setting_default_content_type_markdown: Markdown
        setting_default_content_type_plain: Czysty tekst
        setting_favourite_modal: Pytaj o potwierdzenie przed dodaniem do ulubionych
        setting_skin: Motyw
        setting_system_emoji_font: Użyj systemowej czcionki emotikon (tylko w wypadku odmiany „Glitch”)
      notification_emails:
        trending_link: Nowy, popularny link wymaga przeglądu
        trending_status: Nowy, popularny wpis wymaga przeglądu
        trending_tag: Nowy, popularny tag wymaga przeglądu
