---
uk:
  admin:
    custom_emojis:
      batch_copy_error: 'Виникла помилка при копіюванні деяких вибраних емодзі: %{message}'
      batch_error: 'Сталася помилка: %{message}'
    settings:
      captcha_enabled:
        title: Вимагати нових користувачів проходити CAPTCHA для підтвердження свого облікового запису
      flavour_and_skin:
        title: Оформлення
      hide_followers_count:
        desc_html: Не показувати підписників у профілях користувачів
        title: Приховати лічильник підписників
      other:
        preamble: Різні налаштування glitch-soc не вміщуються в інші категорії.
        title: Інші
      outgoing_spoilers:
        desc_html: При федерації дмухів, додавання цього вмісту попередження до дмухів, яких немає. Це корисно, якщо ваш сервер спеціалізується на інших серверах і може захотіти мати під попередженням про вміст. Медіа також буде відзначена як чутливі.
        title: Попередження про вміст на вихідні дмухи
      show_reblogs_in_public_timelines:
        desc_html: Показати публічні поширення дмухів в локальній та публічній стрічці.
        title: Показати поширення в публічній стрічці
      show_replies_in_public_timelines:
        desc_html: На додачу до публічних само-відповідей (потоків), показувати публічні відповіді на локальній та публічній хронологіях.
        title: Показати відповіді в публічній стрічці
      trending_status_cw:
        desc_html: Якщо увімкнено тренди, дозвольте публікаціям з попередженнями про вміст бути прийнятними. Зміни цього параметра не мають зворотної дії.
        title: Дозволити дописи з попередженнями про вміст у тренді
  appearance:
    localization:
      glitch_guide_link: https://crowdin.com/project/glitch-soc
      glitch_guide_link_text: Так само і для неймовірного glitch-soc!
  auth:
    captcha_confirmation:
      hint_html: Ще один крок! Щоб підтвердити свій обліковий запис, інстанс потребує проходження коду CAPTCHA. Ви можете <a href="/about/more">зв'язатися з адміністратором інстансу</a> , якщо у вас є питання або потрібна допомога з підтвердженням вашого облікового запису.
      title: Верифікація користувача
  generic:
    use_this: Використати це
  settings:
    flavours: Оформлення
