---
zh-TW:
  appearance:
    localization:
      glitch_guide_link: https://crowdin.com/project/glitch-soc
      glitch_guide_link_text: 對於 glitch-soc 來說也是如此！
  auth:
    captcha_confirmation:
      title: 使用者驗證
